return {
  -- "zbirenbaum/copilot.lua",
  -- opts = {
  --   filetypes = {
  --     ["."] = false,
  --     css = false,
  --     cvs = false,
  --     gitcommit = false,
  --     gitrebase = false,
  --     help = false,
  --     hgcommit = false,
  --     markdown = false,
  --     scss = false,
  --     svn = false,
  --     yaml = false,
  --     [""] = false,
  --   },
  --   panel = {
  --     enabled = false,
  --   },
  --   suggestion = {
  --     auto_trigger = true,
  --     keymap = {
  --       accept = "<c-]>",
  --       accept_word = "<a-]>",
  --       accept_line = "<a-[>",
  --       next = "<a-n>",
  --       prev = "<a-p>",
  --       dismiss = "<a-e>",
  --     },
  --   },
  -- },
  -- config = function(_, opts)
  --   local copilot = require("copilot")
  --
  --   copilot.setup(opts)
  -- end,
  --
  -- cmd = "Copilot",
  -- event = "InsertEnter",
}
